version: "3.8"

services:
  app:
    build: .
    container_name: php-todo-app
    ports:
      - "8090:8000"
    # volumes:
    #   - .:/var/www # Testing testing testing
    networks:
      - tooling_app_network
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: ["bash", "/var/www/run-php-server.sh"]
  
  db: 
    image:  mysql:5.7 # 146682692a3a
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
      - ./create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_USER: todouser
      MYSQL_PASSWORD: devopsacts
    networks:
      - tooling_app_network
    
networks:
  tooling_app_network:
    driver: bridge

volumes:
  db_data: